import Head from 'next/head'
import { useEffect, useState } from 'react';
import { CountryData } from '@/types';

export async function getStaticProps() {
  let resp;

  try {
    resp = await fetch("https://restcountries.com/v3.1/all");
  } catch (error) {
    console.log("There was an error", error)
  }

  if (!resp?.ok) {
    console.log(`there was an error, and the HTTP error code is ${resp?.status}`)
  }

  const data = await resp?.json()

  return {
    props: {
      data: data
    }
  }
}

interface Props {
  data: CountryData[]
}

export default function Home({ data }: Props) {
  const [query, setQuery] = useState(""); // state for query
  const [regionFilter, setRegionFilter] = useState("") // state for region filter

  const [paginationActivePage, setPaginationActivePage] = useState(1)


  const filteredData = data.filter((country) => {
    // check if current country's region matches the selected region
    if (country.region.toLowerCase().includes(regionFilter.toLowerCase())) {
      // check if the country's name matches query
      return (country.name.common.toLowerCase().includes(query.toLowerCase()) || country.name.official.toLowerCase().includes(query.toLowerCase()))
    } else {
      // if flase return false so that country get skipped
      return false
    }
  })

  const itemsPerPagination = 12

  const paginationLength = Math.ceil(filteredData.length / itemsPerPagination)

  const indexOfLastPost = paginationActivePage * itemsPerPagination
  const indexOfFirstPost = indexOfLastPost - itemsPerPagination

  const tempData = filteredData.slice(indexOfFirstPost, indexOfLastPost)

  console.log({ query, data, filteredData });

  const numbers: number[] = []

  for (let i = 1; i <= paginationLength; i++) {
    numbers.push(i)
  }

  useEffect(() => {
    setPaginationActivePage(1)
  }, [query, regionFilter])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="">
        <input type="search" value={query} onChange={(e) => {
          setQuery(e.target.value)
        }} />
        <div>
          {tempData.map(country => <div key={country.name.common}>{country.name.official}</div>)}
        </div>
        <div className='flex gap-5 flex-wrap'>
          {numbers.map((number, index) => <button onClick={() => { setPaginationActivePage(index + 1) }} key={number} className="bg-blue-500 rounded-md p-5">{number}</button>)}
        </div>
      </main>
    </>
  )
}
